name: Fetch GitHub Repositories

on:
  schedule:
    - cron: 0 0 * * * # Run daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Prevent multiple workflow runs from overlapping
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Fetch repositories
        run: bun run index.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if changed
        run: |
          git add data/
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "Update repository data - ${timestamp}" || exit 0
          git push
